name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v3
      - name: Build and push the Image
        run: |
          docker login --username codigo3000 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/codigo3000/hello-world-ghcr:latest
          docker push ghcr.io/codigo3000/hello-world-ghcr:latest